		//$usuario = UsuarioControlador::getUsuario($txtCedula, $txtPassword);
		//$_SESSION["usuario"] = array(

			//"id" => $usuario->getId(),
			//"nombre" =>$usuario->getNombre(),
			//"apellido" => $usuario->getApellido(),
			//"tipoDocumento" => $usuario->getTipoDocumento(),
			//"cedula" => $usuario-> getCedula(),
			//"password" => $usuario-> getPassword(),
			//"imagen" => $usuario->  getImagen(),
			//"edad" => $usuario-> getEdad(),
			//"fechaNacimiento" => $usuario-> getFechaNacimiento(),
			//"genero" => $usuario-> getGenero(),
			//"rh" => $usuario->  getRh(),
			//"tipoAsistente" => $usuario-> getTipoAsistente(),
			//"correo" => $usuario-> getCorreo(),
			//"celular" => $usuario-> getCelular(),
			//"direccion" => $usuario-> getDireccion(),
			//"estadoCivil" => $usuario-> getEstadoCivil(),
			//"epsSisben" => $usuario-> getEpsSisben(),
			//"fechaBautizmo" => $usuario-> getFechaBautizmo(),
			//"pastorBautizo" => $usuario-> getPastorBautizo(),
			//"llenoSanto" => $usuario-> getLlenoSanto(),
			//"fecha" => $usuario-> getFecha(),
			//"servidorLocal" => $usuario-> getServidorLocal(),
			//"comite" => $usuario-> getComite(),
			//"cargo" => $usuario-> getCargo(),
			//"privilegio" => $usuario->getPrivilegio(),

		//);